on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: [self-hosted, nathan]
    # runs-on: ubuntu-latest
    name: Compile mesa for the Pinenote
    steps:
      - name: Docker-based compilation
        id: compile-mesa-in-docker
        uses: m-weigand/pinenote_debian_mesa@main
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: mutter
          path: ${{ runner.temp }}/_github_home/mesa_arm64_debs
